.github/workflows/ci.yaml, .github/workflows/deploy-to-testnets.yaml, .github/workflows/publish-master.yaml, examples/README.md, examples/superfluid-auction/contracts/Auction.sol, examples/superfluid-auction/test/Auction.test.js, lerna.json, packages/ethereum-contracts/contracts/interfaces/superfluid/Definitions.sol, packages/ethereum-contracts/contracts/mocks/SuperAppMock.sol, packages/ethereum-contracts/contracts/mocks/SuperfluidMock.sol, packages/ethereum-contracts/contracts/superfluid/Superfluid.sol, packages/ethereum-contracts/contracts/utils/CallUtils.sol, packages/ethereum-contracts/package.json, packages/ethereum-contracts/scripts/deploy-super-token.js, packages/ethereum-contracts/test/contracts/superfluid/Superfluid.test.js, packages/js-sdk/package.json
* Updating examples (#187)
* Security abi decode in termination (#189)
=> Release 0.2.1

packages/ethereum-contracts/package.json, packages/js-sdk/README.md, packages/js-sdk/package.json, packages/js-sdk/src/README.md
* fix deploy-super-token.js 
* protocol release version -> v1
=> Test 0.2.2 release

packages/ethereum-contracts/contracts/mocks/SuperTokenFactoryMock.sol, packages/ethereum-contracts/contracts/mocks/SuperTokenMock.sol, packages/ethereum-contracts/contracts/superfluid/SuperToken.sol, packages/ethereum-contracts/package.json, packages/ethereum-contracts/scripts/deploy-framework.js, packages/ethereum-contracts/scripts/loadContracts.js, packages/ethereum-contracts/test/contracts/superfluid/SuperToken.NonStandard.test.js, packages/ethereum-contracts/test/contracts/superfluid/SuperTokenFactory.test.js
=> PVE001 fix - use SafeERC20 SafeTrasfer(From)

examples/flowlottery/ui/src/App.js, examples/flowlottery/ui/src/components/BottomTables.js, examples/flowlottery/ui/src/components/index.js
This PR introduces some changes to the `flowlottery` demo:
* Fixes error when a user tries to join the lottery: update the list of Txs sent through `batchCall` so they match to the recent release of Superfluid contracts
* Fixes an error when calling the `leaveLottery`: match the `callAgreement` method call to the recent release of Superfluid contracts
* Minor fixes in the UI so warnings/errors disappear from the console
=> [examples] fix flowlottery demo

.github/workflows/ci.yml, .github/workflows/is-pr-external.yml
- do not trigger ci.yml for internal PR
=> improved external PR workflow

.github/workflows/publish-pr.yml, packages/ethereum-contracts/README.md, packages/ethereum-contracts/package.json, packages/ethereum-contracts/scripts/deploy-framework.js, packages/ethereum-contracts/scripts/deploy-super-token.js, packages/ethereum-contracts/scripts/deploy-test-environment.js, packages/ethereum-contracts/scripts/deploy-test-token.js, packages/ethereum-contracts/scripts/getConfig.js, packages/ethereum-contracts/scripts/utils.js, packages/ethereum-contracts/test/deployment.test.js, packages/ethereum-contracts/test/deployment.test.sh, packages/ethereum-contracts/truffle-config.js, packages/js-sdk/package.json, tasks/check-changeset.sh, yarn.lock
- allow more options when invoked as modules
- allow env `DISABLE_NATIVE_TRUFFLE` for disabling truffle native
environment when deploying
=> deployment scripts improvements

packages/ethereum-contracts/package.json, packages/js-sdk/package.json, packages/js-sdk/src/Framework.js, packages/js-sdk/test/Framework.test.js
@param {string[]} options.tokens (Optional) Tokens to be loaded with a list of (in order of preference):
- super chain-native token symbol,
- underlying token symbols,
- super token symbol
=> SDK to be able to load native super token

packages/ethereum-contracts/README.md
Seems like it was missing the word "you"
=> add "you" on line 116

.github/workflows/deploy-to-testnets.yml, packages/ethereum-contracts/contracts/superfluid/SuperToken.sol, packages/ethereum-contracts/contracts/superfluid/SuperTokenFactory.sol, packages/ethereum-contracts/package.json, packages/ethereum-contracts/scripts/deploy-framework.js, packages/ethereum-contracts/scripts/getConfig.js, packages/ethereum-contracts/scripts/utils.js, packages/ethereum-contracts/tasks/etherscan-verify-framework.sh, packages/ethereum-contracts/tasks/supports-etherscan.sh, packages/ethereum-contracts/test/contracts/superfluid/SuperToken.NonStandard.test.js, packages/ethereum-contracts/test/contracts/superfluid/SuperTokenFactory.test.js, packages/ethereum-contracts/truffle-config.js, packages/js-sdk/src/getConfig.js, yarn.lock
=> Deployment fixes

packages/ethereum-contracts/package.json, yarn.lock
Tentative truffle update, triggered by the annoying issue with console globals (https://github.com/trufflesuite/truffle/pull/4242)
I went through the changelog and couldn't see anything looking problematic. As should be with changing minor version.
=> updated truffle to 5.4.10

packages/subgraph/README.md
New readme for graph @hellwolf
=> Review subgraph readme

packages/ethereum-contracts/contracts/utils/TOGA.sol
had the definition of the abbreviation _PIC_wrong in the interface doce
=> fixed PIC definition in interface doc

packages/subgraph/schema.graphql, packages/subgraph/src/mappings/cfav1.ts, packages/subgraph/src/mappings/host.ts, packages/subgraph/src/mappings/idav1.ts, packages/subgraph/src/mappings/resolver.ts, packages/subgraph/src/mappings/superToken.ts, packages/subgraph/src/mappings/superTokenFactory.ts, packages/subgraph/src/mappings/superfluidGovernance.ts, packages/subgraph/src/utils.ts, packages/subgraph/test/helpers/testers.ts, packages/subgraph/test/interfaces.ts, packages/subgraph/test/queries/eventQueries.ts, packages/subgraph/test/validation/eventValidators.ts
- specified in comments which addresses to expect in `schema.graphql`
- tests added for addresses and name
=> name and addresses properties added to event entities

.github/workflows/ci.canary.yml, .github/workflows/ci.feature.yml, packages/sdk-core/test/0_framework.test.ts
- using polygon-rpc.com for tests (framework initialization only)
=> MATIC_PROVIDER_URL removed

packages/subgraph/networks.json, packages/subgraph/package.json, packages/subgraph/tasks/deploy-all-networks.sh, packages/subgraph/tasks/deploy-to-network.sh
=> Subgraph deploy fix

packages/sdk-core/README.md
- added updated query functions to readme
- fixed up cfa/ida/token functions to use operation syntax
- some general formatting
=> readme fixed

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, examples/sdk-redux-react-typecript/src/App.tsx, packages/sdk-core/.eslintignore, packages/sdk-core/.eslintrc.json, packages/sdk-core/package.json, packages/sdk-core/src/BatchCall.ts, packages/sdk-core/src/ConstantFlowAgreementV1.ts, packages/sdk-core/src/Framework.ts, packages/sdk-core/src/Host.ts, packages/sdk-core/src/InstantDistributionAgreementV1.ts, packages/sdk-core/src/Operation.ts, packages/sdk-core/src/Query.ts, packages/sdk-core/src/SuperToken.ts, packages/sdk-core/src/Token.ts, packages/sdk-core/src/frameworkHelpers.ts, packages/sdk-core/src/index.ts, packages/sdk-core/src/interfaces.ts, packages/sdk-core/src/mapGetAllEventsQueryEvents.ts, packages/sdk-core/src/ordering.ts, packages/sdk-core/src/pagination.ts, packages/sdk-core/src/subgraph/SubgraphClient.ts, packages/sdk-core/src/subgraph/queries/getAllEvents.graphql, packages/sdk-core/src/subgraph/schema.graphql, packages/sdk-core/src/utils.ts, packages/sdk-core/src/validation.ts, packages/sdk-redux/.eslintrc.json, packages/sdk-redux/package.json, packages/sdk-redux/src/typings/global.d.ts, yarn.lock
* move dependency to devDependency (correct place)
* remove unused scripts and packages
* make react/redux mandatory peerDependency for now
* add linting to sdk-core project
* Clean-up SDK-Redux demo project
* Update Subgraph schema for SDK-Core
=> Clean up package.jsons of SDK-s & Update SDK-Core's Subgraph schema & Clean up SDK-Redux demo project

packages/sdk-core/README.md
Success at https://rinkeby.etherscan.io/tx/0x315ecfffbbfb13b60a162ef228db8121f732a7a23b3d2867303a5ef4696bcbfe
=> Fix outdated naming of functions

packages/sdk-core/README.md
by adding web3Provider as for the other usecases.
=> Fix: type problem of createSigner

packages/sdk-core/src/Framework.ts, packages/sdk-core/src/Query.ts, packages/sdk-core/src/SFError.ts, packages/sdk-core/src/SuperToken.ts, packages/sdk-core/src/constants.ts, packages/sdk-core/src/frameworkHelpers.ts
Co-Authored-By: Kaspar Kallas <kaspar@superfluid.finance>
- refactored and cleaned up some of the if logic into ternary
- added eslint-disable-next-line for convenience in a few places for now
=> fix eslint warnings on github

.github/ISSUE_TEMPLATE/default-bug-report.md, .github/ISSUE_TEMPLATE/general-bug-report.md, .github/ISSUE_TEMPLATE/sdk-core-bug-report.md, .github/ISSUE_TEMPLATE/sdk-redux-bug-report.md, .github/ISSUE_TEMPLATE/subgraph-bug-report.md
- issue report template created for general bugs (can be used for dashboard, console, etc.)
- issue report templates created for SDKs and subgraph as well
=> Update issue templates

packages/sdk-core/package.json, packages/sdk-core/src/subgraph/.graphqlconfig, packages/sdk-core/tasks/testenv-ctl.sh
- realized that this actually isn't on dev yet, it is part of the 3Ps PR
=> schema.graphql generation

packages/ethereum-contracts/contracts/interfaces/superfluid/ISuperfluidToken.sol, packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol
related: https://github.com/superfluid-finance/superfluid-stories/issues/127
=> makeLiquidationPayoutsV2 contract code added

packages/ethereum-contracts/contracts/agreements/ConstantFlowAgreementV1.sol, packages/ethereum-contracts/contracts/interfaces/agreements/IConstantFlowAgreementV1.sol, packages/ethereum-contracts/test/contracts/agreements/ConstantFlowAgreementV1.test.js
- test cases fixed up for function
- contract fixed up
- interface comments added
=> getDepositRequiredForFlowRate fixed up

.gitignore, .prettierrc.js, packages/ethereum-contracts/.prettierrc.js, packages/ethereum-contracts/package.json, packages/js-sdk/.prettierrc.js, packages/js-sdk/package.json, packages/sdk-core/package.json, packages/sdk-redux/.prettierrc.js, packages/sdk-redux/package.json, packages/subgraph/.prettierrc.js, packages/subgraph/package.json, yarn.lock
For updating truffle-contract versions.
=> Update dependencies for ethereum-contracts/js-sdk & cleaned up prettier usage

.github/workflows/ci.feature.yml, .idea/protocol-monorepo.iml, packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol
=> Simplify make liquidation payouts v2

packages/sdk-core/CHANGELOG.md, packages/sdk-core/src/constants.ts
=> typo fix + constants
